config/routes.rb
Amenoske::Application.routes.draw do
  resources :eventos

  get "tablero/index"

  root :to => 'tablero#index'

end

app/models/evento.rb
class Evento < ActiveRecord::Base
  attr_accessible :descripcion, :fecha, :precio, :ubicacion
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eventos }
    end
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
    @evento = Evento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/new
  # GET /eventos/new.json
  def new
    @evento = Evento.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @evento }
    end
  end

  # GET /eventos/1/edit
  def edit
    @evento = Evento.find(params[:id])
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(params[:evento])

    respond_to do |format|
      if @evento.save
        format.html { redirect_to @evento, notice: 'Evento was successfully created.' }
        format.json { render json: @evento, status: :created, location: @evento }
      else
        format.html { render action: "new" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /eventos/1
  # PUT /eventos/1.json
  def update
    @evento = Evento.find(params[:id])

    respond_to do |format|
      if @evento.update_attributes(params[:evento])
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento = Evento.find(params[:id])
    @evento.destroy

    respond_to do |format|
      format.html { redirect_to eventos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tablero_controller.rb
class TableroController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/helpers/tablero_helper.rb
module TableroHelper
end

app/views/eventos/_form.html.haml
= simple_form_for @evento, :html => { :class => 'form-horizontal' } do |f|
  = f.input :fecha
  = f.input :ubicacion
  = f.input :precio
  = f.input :descripcion
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), eventos_path, :class => 'btn'

app/views/eventos/admin.html.haml
- model_class = Evento
.h-title
  %h2.one
    %span=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:fecha)
      %th= model_class.human_attribute_name(:ubicacion)
      %th= model_class.human_attribute_name(:precio)
      %th= model_class.human_attribute_name(:descripcion)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @eventos.each do |evento|
      %tr
        %td= link_to evento.id, evento_path(evento)
        %td= evento.fecha
        %td= evento.ubicacion
        %td= evento.precio
        %td= evento.descripcion
        %td=l evento.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_evento_path(evento), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), evento_path(evento), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_evento_path, :class => 'btn btn-primary'

app/views/eventos/edit.html.haml
- model_class = Evento
.h-title
  %h2.one
    %span=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}")
= render :partial => "form"

app/views/eventos/index.html.haml
- model_class = Evento
.h-title
  %h2.one
    %span=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:fecha)
      %th= model_class.human_attribute_name(:ubicacion)
      %th= model_class.human_attribute_name(:precio)
  %tbody
    - @eventos.each do |evento|
      %tr
        %td= evento.fecha
        %td= link_to evento.ubicacion, evento_path(evento)
        %td= evento.precio

app/views/eventos/new.html.haml
- model_class = Evento
.h-title
  %h2.one
    %span=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human, :default => "New #{model_class.model_name.human}")
= render :partial => "form"

app/views/eventos/show.html.haml
- model_class = Evento
.h-title
  %h2.one
    %span=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:fecha) + ':'
  %br
  = @evento.fecha
%p
  %strong= model_class.human_attribute_name(:ubicacion) + ':'
  %br
  = @evento.ubicacion
%p
  %strong= model_class.human_attribute_name(:precio) + ':'
  %br
  = @evento.precio
%p
  %strong= model_class.human_attribute_name(:descripcion) + ':'
  %br
  = @evento.descripcion

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), eventos_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_evento_path(@evento), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), evento_path(@evento), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Amenoske"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    %link{:href => "http://fonts.googleapis.com/css?family=Arvo", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans", :rel => "stylesheet", :type => "text/css"}

    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Amenoské
          .nav-collapse
            %ul.nav
              %li
                %a{:href => "/"} Inicio
              %li
                =link_to 'Eventos', eventos_path
              %li
                %a{:href => "photos.html"} Fotos
              %li
                %a{:href => "music.html"} Música
              %li
                %a{:href => "bio.html"} Bio
              %li
                %a{:href => "contact.html"} Contacto
          / /.nav-collapse
    .container
      = yield
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/tablero/index.html.haml
%section#home-content
  / Start Home Content
  .slider-content.drop-shadow.lifted
    / Start Slide Content
    #myCarousel.carousel.slide
      / Carousel items
      .carousel-inner
        .active.item
          %img{:alt => "", :src => image_path("img-1.jpg")}/
        .item
          %img{:alt => "", :src => image_path("img-1.jpg")}/
        .item
          %img{:alt => "", :src => image_path("img-1.jpg")}/
      / Carousel nav
      %a.carousel-control.left{"data-slide" => "prev", :href => "#myCarousel"} ‹
      %a.carousel-control.right{"data-slide" => "next", :href => "#myCarousel"} ›
  / End Slide Content
.h-title
  %h2.one
    %span Noticias
%ul.thumbnails
  %li.box.span3
    .thumbnail
      %img{:alt => "", :src => "http://placehold.it/260x180"}
        %h5 Thumbnail label
        %p Thumbnail caption right here...
  %li.box.span3
    .thumbnail
      %img{:alt => "", :src => "http://placehold.it/260x180"}
        %h5 Thumbnail label
        %p Thumbnail caption right here...
  %li.box.span3
    .thumbnail
      %img{:alt => "", :src => "http://placehold.it/260x180"}
        %h5 Thumbnail label
        %p Thumbnail caption right here...
  %li.box.span3
    .thumbnail
      %img{:alt => "", :src => "http://placehold.it/260x180"}
        %h5 Thumbnail label
        %p Thumbnail caption right here...